// Auto-generated by scripts/deep-research-update.mjs. Do not edit manually.
export const deepResearchSnapshot = {
  "updatedAt": "2026-04-05T05:40:05.121Z",
  "source": {
    "competitionFeed": "https://scores.iplt20.com/ipl/mc/competition.js",
    "scheduleFeed": "https://ipl-stats-sports-mechanic.s3.ap-south-1.amazonaws.com/ipl/feeds/284-matchschedule.js",
    "newsFeed": "https://www.iplt20.com/news",
    "multiSourceFeeds": [
      "https://www.iplt20.com/news",
      "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
      "https://www.cricbuzz.com/cricket-news/rss",
      "https://indianexpress.com/section/sports/cricket/feed/",
      "https://crex.live/",
      "https://www.sportskeeda.com/cricket/rss"
    ]
  },
  "competition": {
    "competitionId": 284,
    "competitionName": "IPL 2026",
    "season": "2026"
  },
  "completedMatches": [
    {
      "matchId": 2425,
      "date": "2026-04-04",
      "team1Code": "RR",
      "team2Code": "GT",
      "team1Score": 210,
      "team2Score": 204,
      "result": "Rajasthan Royals Won by 6  Runs "
    },
    {
      "matchId": 2424,
      "date": "2026-04-04",
      "team1Code": "MI",
      "team2Code": "DC",
      "team1Score": 162,
      "team2Score": 164,
      "result": "Delhi Capitals Won by 6  Wickets "
    },
    {
      "matchId": 2423,
      "date": "2026-04-03",
      "team1Code": "CSK",
      "team2Code": "PBKS",
      "team1Score": 209,
      "team2Score": 210,
      "result": "Punjab Kings Won by 5  Wickets "
    },
    {
      "matchId": 2422,
      "date": "2026-04-02",
      "team1Code": "SRH",
      "team2Code": "KKR",
      "team1Score": 226,
      "team2Score": 161,
      "result": "Sunrisers Hyderabad Won by 65  Runs "
    },
    {
      "matchId": 2421,
      "date": "2026-04-01",
      "team1Code": "LSG",
      "team2Code": "DC",
      "team1Score": 141,
      "team2Score": 145,
      "result": "Delhi Capitals Won by 6  Wickets "
    },
    {
      "matchId": 2420,
      "date": "2026-03-31",
      "team1Code": "GT",
      "team2Code": "PBKS",
      "team1Score": 162,
      "team2Score": 165,
      "result": "Punjab Kings Won by 3  Wickets "
    },
    {
      "matchId": 2419,
      "date": "2026-03-30",
      "team1Code": "CSK",
      "team2Code": "RR",
      "team1Score": 127,
      "team2Score": 128,
      "result": "Rajasthan Royals Won by 8  Wickets "
    },
    {
      "matchId": 2418,
      "date": "2026-03-29",
      "team1Code": "KKR",
      "team2Code": "MI",
      "team1Score": 220,
      "team2Score": 224,
      "result": "Mumbai Indians Won by 6  Wickets "
    },
    {
      "matchId": 2417,
      "date": "2026-03-28",
      "team1Code": "SRH",
      "team2Code": "RCB",
      "team1Score": 201,
      "team2Score": 203,
      "result": "Royal Challengers Bengaluru Won by 6  Wickets "
    }
  ],
  "teamSummary": {
    "csk": {
      "played": 2,
      "won": 0,
      "lost": 2,
      "ties": 0,
      "runsFor": 336,
      "runsAgainst": 338
    },
    "mi": {
      "played": 2,
      "won": 1,
      "lost": 1,
      "ties": 0,
      "runsFor": 386,
      "runsAgainst": 384
    },
    "rcb": {
      "played": 1,
      "won": 1,
      "lost": 0,
      "ties": 0,
      "runsFor": 203,
      "runsAgainst": 201
    },
    "kkr": {
      "played": 2,
      "won": 0,
      "lost": 2,
      "ties": 0,
      "runsFor": 381,
      "runsAgainst": 450
    },
    "dc": {
      "played": 2,
      "won": 2,
      "lost": 0,
      "ties": 0,
      "runsFor": 309,
      "runsAgainst": 303
    },
    "pbks": {
      "played": 2,
      "won": 2,
      "lost": 0,
      "ties": 0,
      "runsFor": 375,
      "runsAgainst": 371
    },
    "rr": {
      "played": 2,
      "won": 2,
      "lost": 0,
      "ties": 0,
      "runsFor": 338,
      "runsAgainst": 331
    },
    "gt": {
      "played": 2,
      "won": 0,
      "lost": 2,
      "ties": 0,
      "runsFor": 366,
      "runsAgainst": 375
    },
    "srh": {
      "played": 2,
      "won": 1,
      "lost": 1,
      "ties": 0,
      "runsFor": 427,
      "runsAgainst": 364
    },
    "lsg": {
      "played": 1,
      "won": 0,
      "lost": 1,
      "ties": 0,
      "runsFor": 141,
      "runsAgainst": 145
    }
  },
  "injuryNews": [
    {
      "title": "KKR, SRH pick player replacements for TATA IPL 2026 24 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4252/kkr-srh-pick-player-replacements-for-tata-ipl-2026",
      "source": "IPLT20"
    },
    {
      "title": "Rajasthan Royals pick player replacement for TATA IPL 2026 23 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4251/rajasthan-royals-pick-player-replacement-for-tata-ipl-2026",
      "source": "IPLT20"
    },
    {
      "title": "Cummins heads back home for final scan on injured back",
      "url": "https://www.espncricinfo.com/ci/content/story/1530422.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Shubman Gill ruled out of GT&#8217;s IPL 2026 clash against RR, Rashid Khan to lead in Ahmedabad",
      "url": "https://indianexpress.com/article/sports/cricket/shubman-gill-ruled-out-gt-vs-rr-rashid-khan-to-lead-10619183/",
      "source": "Indian Express"
    }
  ],
  "researchSources": [
    {
      "name": "IPLT20",
      "url": "https://www.iplt20.com/news",
      "type": "html",
      "success": true,
      "extractedItems": 40,
      "contextualItems": 40
    },
    {
      "name": "ESPNcricinfo",
      "url": "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
      "type": "rss",
      "success": true,
      "extractedItems": 25,
      "contextualItems": 14
    },
    {
      "name": "Cricbuzz",
      "url": "https://www.cricbuzz.com/cricket-news/rss",
      "type": "rss",
      "success": true,
      "extractedItems": 0,
      "contextualItems": 0
    },
    {
      "name": "Indian Express",
      "url": "https://indianexpress.com/section/sports/cricket/feed/",
      "type": "rss",
      "success": true,
      "extractedItems": 25,
      "contextualItems": 24
    },
    {
      "name": "CREX",
      "url": "https://crex.live/",
      "type": "html",
      "success": true,
      "extractedItems": 40,
      "contextualItems": 29
    },
    {
      "name": "Sports Blog Signals",
      "url": "https://www.sportskeeda.com/cricket/rss",
      "type": "rss",
      "success": false,
      "extractedItems": 0,
      "contextualItems": 0,
      "error": "Command failed: python -c from urllib.request import Request, urlopen;import sys;url = sys.argv[1];req = Request(url, headers={'User-Agent': 'Mozilla/5.0', 'Referer': 'https://www.iplt20.com/'});print(urlopen(req, timeout=30).read().decode('utf-8', 'ignore')) https://www.sportskeeda.com/cricket/rss\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/root/.pyenv/versions/3.12.12/lib/python3.12/urllib/request.py\", line 215, in urlopen\n    return opener.open(url, data, timeout)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.12.12/lib/python3.12/urllib/request.py\", line 521, in open\n    response = meth(req, response)\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.12.12/lib/python3.12/urllib/request.py\", line 630, in http_response\n    response = self.parent.error(\n               ^^^^^^^^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.12.12/lib/python3.12/urllib/request.py\", line 559, in error\n    return self._call_chain(*args)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.12.12/lib/python3.12/urllib/request.py\", line 492, in _call_chain\n    result = func(*args)\n             ^^^^^^^^^^^\n  File \"/root/.pyenv/versions/3.12.12/lib/python3.12/urllib/request.py\", line 639, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\nurllib.error.HTTPError: HTTP Error 403: Forbidden\n"
    }
  ],
  "topExternalHeadlines": [
    {
      "title": "Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026 Click here to follow all the LIVE action from TATA WPL 2026",
      "url": "https://www.wplt20.com/?utm_source=website&utm_medium=banner&utm_campaign=wwpl26",
      "source": "IPLT20"
    },
    {
      "title": "Read More Article -->",
      "url": "https://www.iplt20.com/news/4270/tata-ipl-2026-match-9-gt-vs-rr-match-report",
      "source": "IPLT20"
    },
    {
      "title": "Read More Article -->",
      "url": "https://www.iplt20.com/news/4269/tata-ipl-2026-match-8-dc-vs-mi-match-report",
      "source": "IPLT20"
    },
    {
      "title": "Read More Article -->",
      "url": "https://www.iplt20.com/news/4267/tata-ipl-2026-match-7-csk-vs-pbks-match-report",
      "source": "IPLT20"
    },
    {
      "title": "Read More Article -->",
      "url": "https://www.iplt20.com/news/4266/code-of-conduct-breach-match-7-csk-v-pbks",
      "source": "IPLT20"
    },
    {
      "title": "Read More Article -->",
      "url": "https://www.iplt20.com/news/4265/code-of-conduct-breach-match-6-kkr-vs-srh",
      "source": "IPLT20"
    },
    {
      "title": "Code of Conduct Breach - Match 4 - PBKS vs GT 01 Apr, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4262/code-of-conduct-breach-match-4-pbks-vs-gt",
      "source": "IPLT20"
    },
    {
      "title": "Google India and BCCI Partner to Transform the IPL Fan Experience with the AI Mode in Google Search 27 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4257/google-india-and-bcci-partner-to-transform-the-ipl-fan-experience-with-the-ai-mode-in-google-search",
      "source": "IPLT20"
    },
    {
      "title": "BCCI announces schedule for second phase of TATA IPL 2026 26 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4256/bcci-announces-schedule-for-second-phase-of-tata-ipl-2026",
      "source": "IPLT20"
    },
    {
      "title": "Navdeep Saini replaces Harshit Rana in KKR, Kulwant Khejroliya joins GT in place of Prithviraj Yarra 25 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4255/navdeep-saini-replaces-harshit-rana-in-kkr-kulwant-khejroliya-joins-gt-in-place-of-prithviraj-yarra",
      "source": "IPLT20"
    },
    {
      "title": "Spencer Johnson joins CSK for TATA IPL 2026 24 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4254/spencer-johnson-joins-csk-for-tata-ipl-2026",
      "source": "IPLT20"
    },
    {
      "title": "KKR, SRH pick player replacements for TATA IPL 2026 24 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4252/kkr-srh-pick-player-replacements-for-tata-ipl-2026",
      "source": "IPLT20"
    },
    {
      "title": "Rajasthan Royals pick player replacement for TATA IPL 2026 23 Mar, 2026 3 min read --> -->",
      "url": "https://www.iplt20.com/news/4251/rajasthan-royals-pick-player-replacement-for-tata-ipl-2026",
      "source": "IPLT20"
    },
    {
      "title": "Hayden expects GT bowlers to 'keep consistently bowling their best ball'",
      "url": "https://www.espncricinfo.com/ci/content/story/1530540.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Three BCB directors resign in one evening amid ongoing turmoil",
      "url": "https://www.espncricinfo.com/ci/content/story/1530531.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Bishnoi: Worked on 'perfecting my lengths' after difficult 2025",
      "url": "https://www.espncricinfo.com/ci/content/story/1530523.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Mehidy, Litton to remain Bangladesh's ODI and T20I captains until next World Cups",
      "url": "https://www.espncricinfo.com/ci/content/story/1530521.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Sameer Minhas 70 gives Islamabad United a rollicking win over Rawalpindiz",
      "url": "https://www.espncricinfo.com/ci/content/story/1530517.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Du Plooy, Cracknell, Roland-Jones keep Middlesex in command",
      "url": "https://www.espncricinfo.com/ci/content/story/1530460.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    },
    {
      "title": "Clarke, Haynes blunt Somerset after Pennington five-for",
      "url": "https://www.espncricinfo.com/ci/content/story/1530468.html?ex_cid=OTC-RSS",
      "source": "ESPNcricinfo"
    }
  ]
} as const;
